<script src="<?=base_url()?>assets/travello/js/jquery-3.2.1.min.js"></script>
<script src="<?=base_url()?>assets/travello/styles/bootstrap4/popper.js"></script>
<script src="<?=base_url()?>assets/travello/styles/bootstrap4/bootstrap.min.js"></script>
<script src="<?=base_url()?>assets/travello/plugins/OwlCarousel2-2.2.1/owl.carousel.js"></script>
<script src="<?=base_url()?>assets/travello/plugins/Isotope/isotope.pkgd.min.js"></script>
<script src="<?=base_url()?>assets/travello/plugins/scrollTo/jquery.scrollTo.min.js"></script>
<script src="<?=base_url()?>assets/travello/plugins/easing/easing.js"></script>
<script src="<?=base_url()?>assets/travello/plugins/parallax-js-master/parallax.min.js"></script>
<script src="<?=base_url()?>assets/travello/js/custom.js"></script>
<script src="<?=base_url()?>assets/travello/https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyCIwF204lFZg1y4kPSIhKaHEXMLYxxuMhA"></script>
<script src="<?=base_url()?>assets/travello/js/contact.js"></script>
<script src="<?=base_url()?>assets/travello/plugins/greensock/TweenMax.min.js"></script>
<script src="<?=base_url()?>assets/travello/plugins/greensock/TimelineMax.min.js"></script>
<script src="<?=base_url()?>assets/travello/plugins/scrollmagic/ScrollMagic.min.js"></script>
<script src="<?=base_url()?>assets/travello/plugins/greensock/animation.gsap.min.js"></script>
<script src="<?=base_url()?>assets/travello/plugins/greensock/ScrollToPlugin.min.js"></script>
<script src="<?=base_url()?>assets/travello/js/about.js"></script>
